# ref:
#  Publishing packages to GitHub Packages:
#    https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-github-packages
#  Events that trigger workflows:
#    https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release
#  Using events to trigger workflows - Using activity types and filters with multiple events:
#    https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#using-activity-types-and-filters-with-multiple-events
#
name: Package Auto Publish
run-name: 'Package Publish #${{github.run_number}}'
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          server-id: 'github-package'
      - name: checkout repo
        uses: actions/checkout@v4
      - name: deploy project with maven
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_MAVEN_URL: https://maven.pkg.github.com/${{github.repository}}
